CREATE TABLE "GCG_6079_BOM_ISS_CR"(
 "PARENT" CHAR(20) CASE,
 "PART" CHAR(20) CASE,
 "LEVEL" BIGINT,
 "QUANTITY" DOUBLE,
 "DESCRIPTION" CHAR(30) CASE,
 "ONHAND" DOUBLE,
 "TERMINAL" CHAR(3) CASE,
 "UM" CHAR(2) CASE,
 "FLAG" BIGINT DEFAULT '0',
 "SEQU" CHAR(10) CASE,
 "ISSUE" DOUBLE,
 "ID" BIGINT );